CREATE TABLE IF NOT EXISTS `users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`username`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`forename`	TEXT NOT NULL DEFAULT ' ',
	`surname`	TEXT NOT NULL DEFAULT ' '
);

CREATE TABLE IF NOT EXISTS `priority` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`level`	TEXT UNIQUE NOT NULL
);

INSERT OR IGNORE INTO priority VALUES (1,'Lowest'), (2,'Low'), (3,'Medium'), (4,'High'), (5,'Highest');


CREATE TABLE IF NOT EXISTS `tasks` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`description`	TEXT NOT NULL,
	`priority_id`	INTEGER NOT NULL,
	FOREIGN KEY(`priority_id`) REFERENCES `priority`(`id`)
);

CREATE TABLE IF NOT EXISTS `collaborators` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user_id`	INTEGER NOT NULL,
	`task_id`	INTEGER NOT NULL,
	FOREIGN KEY(`task_id`) REFERENCES `tasks`(`id`),
	FOREIGN KEY(`user_id`) REFERENCES `users`(`id`)
);